name: gosec
version: 2.11.0
summary: Golang Security Checker
description: |
  Inspects source code for security problems by scanning the Go AST.

base: core18
confinement: strict
grade: stable

apps:
  gosec:
    command: gosec
    plugs:
      - home
      - network

parts:
  gosec:
    plugin: make
    source: https://github.com/securego/gosec.git
    source-tag: v$SNAPCRAFT_PROJECT_VERSION
    build-packages:
      - git
      - gcc
    build-snaps:
      - go
    override-build: |
      snapcraftctl build
      cp gosec $SNAPCRAFT_PART_INSTALL

  # gosec requires a go binary in $PATH so use the go snap for this
  go:
    plugin: nil
    stage-snaps:
    - go

