name: gosec
version: 2.7.0
summary: Golang Security Checker
grade: stable
description: |
  Inspects source code for security problems by scanning the Go AST.

base: core20
confinement: strict
architectures: [amd64]

apps:
  gosec:
    command: bin/gosec
    plugs:
      - home
      - network

parts:
  gosec:
    plugin: dump
    source: https://github.com/securego/gosec/releases/download/v${SNAPCRAFT_PROJECT_VERSION}/gosec_${SNAPCRAFT_PROJECT_VERSION}_linux_amd64.tar.gz
    organize:
      gosec: bin/
    stage:
      - -README.md
      - -LICENSE.txt

  # gosec requires a go binary in $PATH so use the go snap for this
  go:
    plugin: nil
    stage-snaps:
      - go
    stage-packages:
      - libc6
