name: gosec
version: 2.13.1
summary: Golang Security Checker
description: |
  Inspects source code for security problems by scanning the Go AST.
license: Apache-2.0

base: core20
confinement: strict
grade: stable

apps:
  gosec:
    command: gosec
    plugs:
      - home
      - network

parts:
  gosec:
    plugin: make
    source: https://github.com/securego/gosec.git
    source-tag: v$SNAPCRAFT_PROJECT_VERSION
    build-packages:
      - git
      - gcc
    build-snaps:
      - go
    stage-snaps:
      - go
    # call the built-in build-linux target
    make-parameters:
      - build-linux
    override-build: |
      # build-linux hardcodes GOARCH so remove that to suport
      sed -i 's/GOARCH=amd64 //' Makefile
      snapcraftctl build
      cp gosec $SNAPCRAFT_PART_INSTALL
